name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: valeriangalliat/action-sshd-cloudflared@v1
    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
