name: CI
on:
  repository_dispatch:
    types: [start]
  workflow_dispatch:
jobs:
  deploy:
    name: Set up tunnel
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup tunnel
      uses: joshlarsen/ssh-tunnel-action@main
      with:
        timeout: 3h
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
    
    #  - uses: actions/checkout@v2
    #  - uses: valeriangalliat/action-sshd-cloudflared@v2
    
    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
